### ISSUE TITLE
BlackScreen when closing Camera on iOS

### ISSUE THREAD

**Issue by marwonline** [trigger-corp/trigger.io-capture#1]
Hi @antoinevg ,

today we found an issue of the this module `2.24` in combination with the forge version `v2.8.1`.

Whenever closing (cancel or send) the Camera (video or image) our app stays black. 

Devices and Versions: 

- iPhone 6s - 13.1.1
- iPhone 7 - 13.1.2
- iPhone 8 Max - 12.4.1

**Comment by marwonline** [comment]
@antoinevg This bug affects all iOS versions on all devices this is **very urgent** as we planned to release last week.

Also selecting an image in the iOS gallery freezes the gallery itself on iOS 11.4.1

**Comment by antoinevg** [comment]
Thank you for the report, it turns out to be a similar issue to the one we had with the Xcode 11.0 GM release here:

https://github.com/trigger-corp/trigger.io-tabs/commit/352d185ccc3512e95c0ea2f73cb53866cebaaeec

Fix has been pushed to `v2.25` of the module.

re: iOS 11.4.1 gallery freeze - this tests okay for me in the simulator, but you may want to double check on hardware if you have it available.
